"""initial schema

Revision ID: cd5010d36f34
Revises: 
Create Date: 2026-07-14 14:53:16.018816

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cd5010d36f34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('jd_filename', sa.String(length=255), nullable=True),
    sa.Column('search_strings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('platform_scope', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_user_id'), 'searches', ['user_id'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('original_position', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relevance_reasoning', sa.Text(), nullable=True),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('is_starred', sa.Boolean(), nullable=False),
    sa.Column('is_recruited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_search_id'), 'search_results', ['search_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_search_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_searches_user_id'), table_name='searches')
    op.drop_table('searches')
    op.drop_table('users')
    # ### end Alembic commands ###
